language: php
php:
  - 5.3

env:
  - SYMFONY_VERSION=v2.0.12
  - SYMFONY_VERSION=origin/2.0
  - SYMFONY_VERSION=origin/master

before_script: php Tests/tests/vendors.php
script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/intl/master/travis
